### ISSUE TITLE
TypeError: this.state.customerDetails.data.map is not a function

### ISSUE THREAD

**Issue by Shuhui11** [aditya-sridhar/simple-reactjs-app#5]
Hi @aditya-sridhar , I am trying to replicate the 3 panel view below the 3 profiles, after I clicked the button "Click to view details". Is something like a family tree, where I click to view details of the father and out pops his 3 children at the bottom.

I changed the customer1.json file into a similar format as the customerlist.json and then change the render part in CustomerDetails.js to the following (trying to replicate that in Customers.js) and encountered the errors:
- TypeError: this.state.customerDetails.data.map is not a function) and Unhandled Rejection
- (TypeError): this.state.customerDetails.data.map is not a function

This is the part that I changed in CustomerDetails.js
![Screenshot 2020-01-22 at 3 38 01 PM](https://user-images.githubusercontent.com/47220371/72874516-2f068300-3d2d-11ea-8984-94a4046d68f7.png)

**Comment by 1209simran** [comment]
Hey @Shuhui11 
 
**JSON for customer1 should look like this:-**

[
  {
    "id": 1,
    "name": "ABCD",
    "email": "jsmith@test.com",
    "phone": "123456789"
  },
  {
    "id": 2,
    "name": "QWER",
    "email": "abcd@test.com",
    "phone": "987654321"
  },
  {
    "id": 3,
    "name": "ABNSD",
    "email": "tyrion@test.com",
    "phone": "123412345"
  }
]


**CustomerDetails should look like this**

import React, { Component } from "react";
import Panel from "react-bootstrap/lib/Panel";
import axios from "axios";

//This Component is a child Component of Customers Component
export default class CustomerDetails extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  //Function which is called when the component loads for the first time
  componentDidMount() {
    this.getCustomerDetails(this.props.val);
  }

  //Function which is called whenver the component is updated
  componentDidUpdate(prevProps) {
    //get Customer Details only if props has changed
    if (this.props.val !== prevProps.val) {
      this.getCustomerDetails(this.props.val);
    }
  }

  //Function to Load the customerdetails data from json.
  getCustomerDetails(id) {
    axios.get("assets/samplejson/customer" + id + ".json").then(response => {
      this.setState({ customerDetails: response });
    });
  }

  render() {
    if (!this.state.customerDetails) return <p>Loading data</p>;
    return (
      <div className="customerdetails">
        <div className="addmargin">
          <div className="col-md-3">
            {this.state.customerDetails.data.map(customer => (
              <Panel bsStyle="info" key={customer.name} className="centeralign">
                <Panel.Heading>
                  <Panel.Title componentClass="h3">{customer.name}</Panel.Title>
                </Panel.Heading>
              </Panel>
            ))}
          </div>
        </div>
      </div>
    );
  }
}

**Comment by Shuhui11** [comment]
Hi @1209simran 

It works! That helps a lot! Thank you for the prompt guidance. I am new and learning.
